export const foodItems = [
  {
    id: 1,
    name: "Intense Shampoo",
    price: 20,
    quantity: 1000,
    desc: "This is a shampoo powered by Intense",
    img: "https://m.media-amazon.com/images/I/71dgpx4e0OL.jpg",
  },
  {
    id: 2,
    name: "Boat Headphone",
    price: 2000,
    quantity: 500,
    desc: "This is a smart headphone product exclusively powered by Boat",
    img: "https://www.boat-lifestyle.com/cdn/shop/products/e5881832-36f8-4c1c-a767-10f2c2a55a02_288x.png?v=1685708053",
  },
  {
    id: 3,
    name: "Dabur Amla Oil",
    price: 150,
    quantity: 430,
    desc: "This is a Hair Oil powered by Dabur Amla Brand.",
    img: "https://m.media-amazon.com/images/I/71FlO3G++cL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 4,
    name: "Redbull Soft Drink",
    price: 100,
    quantity: 500,
    desc: "This is a Redbull Drink Soft Drink.",
    img: "https://www.shutterstock.com/image-photo/klangmalaysia-circa-may-2020-picture-260nw-1726155472.jpg",
  },
  {
    id: 5,
    name: "Santoor Soap",
    price: 50,
    quantity: 300,
    desc: "This is a Soap product powered by Santoor",
    img: "https://m.media-amazon.com/images/I/81k5V7MNGlL.jpg",
  },
];
